# Generated by Django 3.2.20 on 2023-07-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
