# Generated by Django 3.2.20 on 2023-07-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_question_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
