# Generated by Django 3.2.20 on 2023-07-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_rename_creator_id_question_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
