# Generated by Django 3.2.20 on 2023-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20230706_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.IntegerField(),
        ),
    ]
