# Generated by Django 3.2.20 on 2023-07-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_question_quiz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz'),
            preserve_default=False,
        ),
    ]
