# Generated by Django 3.2.20 on 2023-07-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20230707_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='answers',
            field=models.ManyToManyField(to='Quiz.Answer'),
        ),
    ]
